import {
  ConstraintProfile,
  MainParameters,
  CleanroomZone,
  EnvironmentalExcursion,
  DefectReductionAction,
  WaferLayerConfig,
} from '../types';

export const PROCESS_LAYER_DEFINITIONS: WaferLayerConfig[] = [
  {
    id: 'L1-SUBSTRATE',
    name: 'Substrate & Well Implant',
    shortCode: 'L1 Substrate',
    category: 'FEOL',
    stackOrder: 1,
    thicknessNm: 775000,
    criticalFeatureNm: 90,
    overlayToleranceNm: 8.0,
    baseDefectRate: 1.4,
    sensitivities: {
      particle: 0.5,
      lithoOverlay: 0.3,
      cdVariation: 0.4,
      temperature: 1.8,
      relativeHumidity: 0.3,
    },
    dominantDefectTypes: ['Random defect', 'Scratch'],
    cleanroomBay: 'Bay 04 - Diffusion & Furnace',
    toolType: 'Applied Materials Varian VIISta High-Current Implanter',
    colorHex: '#64748b', // Slate silicon
    metallic: 0.8,
    roughness: 0.2,
    opacity: 0.95,
    description: 'Bulk silicon substrate and deep well implants defining active conduction channels. Susceptible to crystal dislocations and furnace thermal gradients.',
  },
  {
    id: 'L2-FIN',
    name: 'Fin Formation & Shallow Trench Isolation (STI)',
    shortCode: 'L2 Fin STI',
    category: 'FEOL',
    stackOrder: 2,
    thicknessNm: 65,
    criticalFeatureNm: 7.0,
    overlayToleranceNm: 2.8,
    baseDefectRate: 4.6,
    sensitivities: {
      particle: 1.2,
      lithoOverlay: 1.5,
      cdVariation: 3.1, // Highest CD sensitivity
      temperature: 1.2,
      relativeHumidity: 1.0,
    },
    dominantDefectTypes: ['Critical-dimension variation', 'Pattern distortion', 'Cluster defect'],
    cleanroomBay: 'Bay 03 - Plasma Dry Etch',
    toolType: 'Lam Research Sense.i Etch Chamber',
    colorHex: '#0284c7', // Cyan FinFET
    metallic: 0.5,
    roughness: 0.3,
    opacity: 0.9,
    description: '3D vertical silicon fin patterning with high aspect ratio dry etch. Vulnerable to fin pitch walk, line-edge roughness, and fin bending/collapse.',
  },
  {
    id: 'L3-GATE',
    name: 'Poly / High-k Metal Gate (HKMG EUV)',
    shortCode: 'L3 Gate HKMG',
    category: 'FEOL',
    stackOrder: 3,
    thicknessNm: 22,
    criticalFeatureNm: 5.0,
    overlayToleranceNm: 1.6, // Strictest overlay budget in fab!
    baseDefectRate: 9.2, // Highest baseline defect risk in chip
    sensitivities: {
      particle: 2.5,
      lithoOverlay: 3.6, // Extreme overlay sensitivity!
      cdVariation: 2.8,
      temperature: 1.9,
      relativeHumidity: 2.4, // CAR resist footing & collapse
    },
    dominantDefectTypes: ['Lithography misalignment', 'Particle contamination', 'Critical-dimension variation'],
    cleanroomBay: 'Bay 01 - Lithography Exposure',
    toolType: 'ASML Twinscan EXE:5000 High-NA EUV Scanner',
    colorHex: '#f59e0b', // Amber / Gold Gate
    metallic: 0.7,
    roughness: 0.25,
    opacity: 0.9,
    description: 'Atomic layer deposition (ALD) high-k gate oxide and EUV-patterned workfunction metal gate. Ground-zero for killer overlay misalignment and nano-bridge shorts.',
  },
  {
    id: 'L4-CONTACT',
    name: 'Middle-of-Line (MOL) Source/Drain Contact',
    shortCode: 'L4 Contact (CA)',
    category: 'MOL',
    stackOrder: 4,
    thicknessNm: 50,
    criticalFeatureNm: 11.0,
    overlayToleranceNm: 2.2,
    baseDefectRate: 5.8,
    sensitivities: {
      particle: 2.2,
      lithoOverlay: 2.6,
      cdVariation: 2.0,
      temperature: 0.9,
      relativeHumidity: 1.2,
    },
    dominantDefectTypes: ['Lithography misalignment', 'Particle contamination', 'Cluster defect'],
    cleanroomBay: 'Bay 03 - Plasma Dry Etch & ALD',
    toolType: 'Applied Materials Endura Cobalt Contact Metallization',
    colorHex: '#8b5cf6', // Violet Contact
    metallic: 0.6,
    roughness: 0.35,
    opacity: 0.85,
    description: 'High aspect ratio tungsten/cobalt contact plugs connecting transistor terminals to Metal 1. Extreme risk of gate-to-contact bridge shorts when overlay drifts.',
  },
  {
    id: 'L5-M1',
    name: 'Metal 1 (M1 Interconnect Damascene)',
    shortCode: 'L5 Metal 1',
    category: 'BEOL',
    stackOrder: 5,
    thicknessNm: 40,
    criticalFeatureNm: 22.0,
    overlayToleranceNm: 3.2,
    baseDefectRate: 7.4,
    sensitivities: {
      particle: 3.4, // Highest particle sensitivity in BEOL
      lithoOverlay: 1.8,
      cdVariation: 1.6,
      temperature: 1.1,
      relativeHumidity: 1.6,
    },
    dominantDefectTypes: ['Particle contamination', 'Pattern distortion', 'Scratch'],
    cleanroomBay: 'Bay 04 - Chemical Mechanical Planarization (CMP)',
    toolType: 'Applied Materials Reflexion LK CMP System',
    colorHex: '#06b6d4', // Teal copper
    metallic: 0.9,
    roughness: 0.15,
    opacity: 0.88,
    description: 'Tightest copper interconnect pitch. Severe vulnerability to CMP slurry micro-scratches, copper dishing, and airborne particle bridge shorts.',
  },
  {
    id: 'L6-M2',
    name: 'Via 1 & Metal 2 (M2 Power Grid)',
    shortCode: 'L6 Via1 / M2',
    category: 'BEOL',
    stackOrder: 6,
    thicknessNm: 75,
    criticalFeatureNm: 36.0,
    overlayToleranceNm: 4.5,
    baseDefectRate: 3.8,
    sensitivities: {
      particle: 2.1,
      lithoOverlay: 1.4,
      cdVariation: 1.2,
      temperature: 0.8,
      relativeHumidity: 1.8,
    },
    dominantDefectTypes: ['Environmental excursion', 'Particle contamination', 'Random defect'],
    cleanroomBay: 'Bay 04 - CMP & Dual Damascene',
    toolType: 'Lam Research SABRE 3D Copper Electroplating',
    colorHex: '#3b82f6', // Cobalt Blue metal
    metallic: 0.85,
    roughness: 0.2,
    opacity: 0.85,
    description: 'Inter-tier copper routing and low-k dielectric layers. Moisture absorption can trigger low-k dielectric fracture and via voids.',
  },
  {
    id: 'L7-PAD',
    name: 'Top Metallization & Passivation',
    shortCode: 'L7 Passivation',
    category: 'BEOL',
    stackOrder: 7,
    thicknessNm: 850,
    criticalFeatureNm: 80.0,
    overlayToleranceNm: 10.0,
    baseDefectRate: 2.1,
    sensitivities: {
      particle: 1.0,
      lithoOverlay: 0.4,
      cdVariation: 0.5,
      temperature: 0.7,
      relativeHumidity: 1.1,
    },
    dominantDefectTypes: ['Edge damage', 'Scratch', 'Random defect'],
    cleanroomBay: 'Bay 05 - Metrology & Final Test',
    toolType: 'Tokyo Electron Trias Titanium/Nitride Passivation CVD',
    colorHex: '#10b981', // Emerald seal
    metallic: 0.4,
    roughness: 0.3,
    opacity: 0.8,
    description: 'Protective silicon nitride/polyimide seal and wire-bond / micro-bump I/O pads. High mechanical stress sensitivity around perimeter.',
  },
];

export const PROTOTYPE_DEFAULT_PARAMETERS: MainParameters = {
  particleContamination: 0.38, // particles/cm²
  lithoAlignmentError: 2.1, // nm
  cdDeviation: 0.95, // nm
  temperature: 21.2, // °C
  relativeHumidity: 42.4, // %
};

export const DEFAULT_CONSTRAINT_PROFILE: ConstraintProfile = {
  id: 'PROFILE-N7-DEMO-01',
  name: '7nm FinFET Production Screening (Demo)',
  version: 'v2.4-Demo',
  processNode: '7nm FinFET',
  waferDiameterMm: 300,
  dieSizeMm: { x: 12, y: 12 },
  edgeExclusionMm: 3.5,
  defectDensityLimit: 0.85,
  modelConfidenceThreshold: 75,
  randomNoiseLevel: 0.08,
  batchVariationStdDev: 0.12,
  batchDriftTrend: 0.04,
  approvalStatus: 'Approved',
  notes: 'Prototype baseline configuration for 300mm sub-10nm lithography qualification. Demo values are calibrated against typical FinFET baseline targets.',
  lastUpdated: '2026-09-15',
  isDefault: true,
  paramConfigs: {
    particleContamination: {
      key: 'particleContamination',
      label: 'Particle Contamination Level',
      unit: 'particles/cm²',
      description: 'Quantifies airborne and surface micro-particulates (>0.1µm) deposited on the wafer substrate, threatening killer defects in active gate patterns.',
      min: 0,
      max: 5.0,
      normalMin: 0,
      normalMax: 0.5,
      warningMin: 0.5,
      warningMax: 1.5,
      weight: 1.25,
    },
    lithoAlignmentError: {
      key: 'lithoAlignmentError',
      label: 'Lithography Alignment Error',
      unit: 'nm',
      description: 'Overlay deviation between scanner reticle exposure field and existing fiducial alignment marks on underlying layers.',
      min: 0,
      max: 15.0,
      normalMin: 0,
      normalMax: 2.5,
      warningMin: 2.5,
      warningMax: 4.5,
      weight: 1.4,
    },
    cdDeviation: {
      key: 'cdDeviation',
      label: 'Critical Dimension Deviation',
      unit: 'nm',
      description: 'The geometric delta between target line/space gate width and post-etch measured feature dimensions across dense arrays.',
      min: 0,
      max: 10.0,
      normalMin: 0,
      normalMax: 1.2,
      warningMin: 1.2,
      warningMax: 2.5,
      weight: 1.15,
    },
    temperature: {
      key: 'temperature',
      label: 'Cleanroom Temperature',
      unit: '°C',
      description: 'Chamber and cleanroom ambient temperature. Direct driver of optical thermal expansion, stage drift, and photoresist bake uniformities.',
      min: 15.0,
      max: 30.0,
      normalMin: 20.5,
      normalMax: 22.0,
      warningMin: 19.5,
      warningMax: 23.0,
      weight: 0.85,
    },
    relativeHumidity: {
      key: 'relativeHumidity',
      label: 'Relative Humidity',
      unit: '%',
      description: 'Cleanroom ambient relative humidity. Influences static charge generation, amine absorption on chemically amplified resists (CAR), and airborne particle suspension.',
      min: 20.0,
      max: 70.0,
      normalMin: 40.0,
      normalMax: 45.0,
      warningMin: 37.0,
      warningMax: 50.0,
      weight: 0.75,
    },
  },
  severityWeights: {
    minor: 0.25,
    warning: 0.6,
    probable: 1.2,
    severe: 2.5,
  },
};

export const ALTERNATIVE_CONSTRAINT_PROFILE: ConstraintProfile = {
  id: 'PROFILE-5NM-GAA-DEMO-02',
  name: '5nm GAA Tight Tolerance Envelope',
  version: 'v3.1-Prototype',
  processNode: '5nm GAA',
  waferDiameterMm: 300,
  dieSizeMm: { x: 10, y: 10 },
  edgeExclusionMm: 2.5,
  defectDensityLimit: 0.45,
  modelConfidenceThreshold: 80,
  randomNoiseLevel: 0.05,
  batchVariationStdDev: 0.09,
  batchDriftTrend: 0.02,
  approvalStatus: 'Review Required',
  notes: 'Aggressive gate-all-around nano-sheet specifications requiring stricter EUV overlay boundaries and tighter humidity bands to prevent line-edge roughness.',
  lastUpdated: '2026-09-17',
  isDefault: false,
  paramConfigs: {
    particleContamination: {
      key: 'particleContamination',
      label: 'Particle Contamination Level',
      unit: 'particles/cm²',
      description: 'Tightened particle ceiling for EUV pellicle and pellicle-less direct wafer exposure.',
      min: 0,
      max: 4.0,
      normalMin: 0,
      normalMax: 0.3,
      warningMin: 0.3,
      warningMax: 0.9,
      weight: 1.5,
    },
    lithoAlignmentError: {
      key: 'lithoAlignmentError',
      label: 'Lithography Alignment Error',
      unit: 'nm',
      description: 'EUV scanner multi-patterning overlay ceiling for sub-20nm pitch lithography.',
      min: 0,
      max: 10.0,
      normalMin: 0,
      normalMax: 1.8,
      warningMin: 1.8,
      warningMax: 3.2,
      weight: 1.6,
    },
    cdDeviation: {
      key: 'cdDeviation',
      label: 'Critical Dimension Deviation',
      unit: 'nm',
      description: 'Nano-sheet channel width CD variance threshold.',
      min: 0,
      max: 8.0,
      normalMin: 0,
      normalMax: 0.8,
      warningMin: 0.8,
      warningMax: 1.8,
      weight: 1.35,
    },
    temperature: {
      key: 'temperature',
      label: 'Cleanroom Temperature',
      unit: '°C',
      description: 'Precision interferometer temperature window for EUV immersion chuck.',
      min: 18.0,
      max: 26.0,
      normalMin: 20.8,
      normalMax: 21.6,
      warningMin: 20.0,
      warningMax: 22.4,
      weight: 0.95,
    },
    relativeHumidity: {
      key: 'relativeHumidity',
      label: 'Relative Humidity',
      unit: '%',
      description: 'Precision environmental humidity control to prevent CAR resist degradation.',
      min: 30.0,
      max: 60.0,
      normalMin: 41.0,
      normalMax: 44.0,
      warningMin: 39.0,
      warningMax: 47.0,
      weight: 0.8,
    },
  },
  severityWeights: {
    minor: 0.35,
    warning: 0.8,
    probable: 1.5,
    severe: 3.0,
  },
};

export const CLEANROOM_ZONES: CleanroomZone[] = [
  {
    id: 'ZONE-LITHO-BAY1',
    name: 'Lithography Exposure Bay 1',
    bayNumber: 'Bay 01-A',
    isoClass: 'ISO Class 1 (FS209E Class 1)',
    temperatureC: 21.3,
    tempStatus: 'normal',
    relativeHumidityPct: 42.6,
    rhStatus: 'normal',
    particleCount: 8, // particles/m3 >=0.1um
    particleStatus: 'normal',
    airflowVelocityMps: 0.45,
    pressureDiffPa: 24.5,
    alertLevel: 'normal',
    activeTool: 'ASML Twinscan EXE:5000 High-NA EUV',
    toolStatus: 'Operational',
    recentExcursionsCount: 0,
    coordinates: { x: -8, z: -5 },
  },
  {
    id: 'ZONE-TRACK-BAY2',
    name: 'Photoresist Track & Coater Bay',
    bayNumber: 'Bay 02-B',
    isoClass: 'ISO Class 2',
    temperatureC: 21.8,
    tempStatus: 'normal',
    relativeHumidityPct: 44.1,
    rhStatus: 'normal',
    particleCount: 22,
    particleStatus: 'normal',
    airflowVelocityMps: 0.42,
    pressureDiffPa: 20.2,
    alertLevel: 'normal',
    activeTool: 'Tokyo Electron CLEAN TRACK LITHIUS Pro Z',
    toolStatus: 'Operational',
    recentExcursionsCount: 1,
    coordinates: { x: -3, z: -5 },
  },
  {
    id: 'ZONE-ETCH-BAY3',
    name: 'Plasma Dry Etch Bay',
    bayNumber: 'Bay 03-C',
    isoClass: 'ISO Class 3',
    temperatureC: 22.4,
    tempStatus: 'warning',
    relativeHumidityPct: 46.8,
    rhStatus: 'warning',
    particleCount: 54,
    particleStatus: 'warning',
    airflowVelocityMps: 0.38,
    pressureDiffPa: 16.8,
    alertLevel: 'warning',
    activeTool: 'Lam Research Sense.i Etch Chamber',
    toolStatus: 'Warning',
    recentExcursionsCount: 3,
    coordinates: { x: 3, z: -5 },
  },
  {
    id: 'ZONE-CMP-BAY4',
    name: 'Chemical Mechanical Planarization (CMP)',
    bayNumber: 'Bay 04-D',
    isoClass: 'ISO Class 3',
    temperatureC: 21.5,
    tempStatus: 'normal',
    relativeHumidityPct: 43.0,
    rhStatus: 'normal',
    particleCount: 38,
    particleStatus: 'normal',
    airflowVelocityMps: 0.41,
    pressureDiffPa: 18.0,
    alertLevel: 'normal',
    activeTool: 'Applied Materials Reflexion LK CMP System',
    toolStatus: 'Operational',
    recentExcursionsCount: 0,
    coordinates: { x: 8, z: -5 },
  },
  {
    id: 'ZONE-METRO-BAY5',
    name: 'Inline CD-SEM & KLA Optical Metrology',
    bayNumber: 'Bay 05-E',
    isoClass: 'ISO Class 1',
    temperatureC: 21.1,
    tempStatus: 'normal',
    relativeHumidityPct: 41.9,
    rhStatus: 'normal',
    particleCount: 12,
    particleStatus: 'normal',
    airflowVelocityMps: 0.46,
    pressureDiffPa: 26.1,
    alertLevel: 'normal',
    activeTool: 'KLA 2935 Broad-Band Optical Wafer Inspector',
    toolStatus: 'Operational',
    recentExcursionsCount: 0,
    coordinates: { x: 0, z: 4 },
  },
];

export const RECENT_EXCURSIONS: EnvironmentalExcursion[] = [
  {
    id: 'EXC-2026-0918-01',
    timestamp: '2026-09-18 09:42:15',
    zoneId: 'ZONE-ETCH-BAY3',
    zoneName: 'Plasma Dry Etch Bay (Bay 03-C)',
    parameter: 'Temperature & Particle Spike',
    measuredValue: '22.8 °C / 68 part/m³',
    thresholdValue: '22.0 °C / 45 part/m³',
    severity: 'Warning',
    potentialWaferImpact: 'Increased probability of edge-ring particulate defects and thermal CD bias on outgoing lots.',
    status: 'Investigating',
  },
  {
    id: 'EXC-2026-0917-02',
    timestamp: '2026-09-17 14:15:00',
    zoneId: 'ZONE-TRACK-BAY2',
    zoneName: 'Photoresist Track Bay',
    parameter: 'Relative Humidity Transient',
    measuredValue: '48.2 % RH',
    thresholdValue: '45.0 % RH max',
    severity: 'Warning',
    potentialWaferImpact: 'Moisture uptake on resist bake step; potential 0.3nm CD broadening across wafer perimeter.',
    status: 'Resolved',
  },
];

export const DEFAULT_DEFECT_ACTIONS: DefectReductionAction[] = [
  {
    id: 'ACTION-001',
    urgency: 'Immediate containment',
    suspectedCause: 'Lithography Scanner Chuck Particulate or Reticle Stage Misalignment',
    evidence: 'High alignment error (2.8nm > 2.5nm threshold) coupled with systematic directional overlay offsets in quadrant 2.',
    affectedWafers: ['WFR-300-8841-01', 'WFR-300-8841-04'],
    affectedDiesCount: 38,
    confidenceScore: 88,
    recommendedAction: 'Execute automated reticle magnification recalibration and inspect wafer chuck vacuum pins for ceramic particle contamination.',
    expectedEffect: 'Expected to reduce lithography alignment error by 0.9nm to 1.4nm, reclaiming ~4.2% die yield.',
    verificationStep: 'Run 1 pilot test wafer through Litho Bay 1 with optical overlay fiducial metrology before releasing production batch.',
    status: 'Approved',
  },
  {
    id: 'ACTION-002',
    urgency: 'Process investigation',
    suspectedCause: 'Post-CMP Slurry Residue / Cleanroom Airborne Particulates',
    evidence: 'Particle contamination measured at 0.72 particles/cm² with cluster defect patterns near wafer bevel edge.',
    affectedWafers: ['WFR-300-8841-03', 'WFR-300-8841-07', 'WFR-300-8841-09'],
    affectedDiesCount: 52,
    confidenceScore: 82,
    recommendedAction: 'Check FOUP carrier cleanliness, verify Megasonic rinse chamber nozzle pressures, and perform HEPA filter air-velocity sweep in Bay 3.',
    expectedEffect: 'Estimated 35% reduction in particle-induced killer defects on upper interconnect metallization layers.',
    verificationStep: 'Inspect laser particle count inside FOUP #18 after automated chemical cleaning cycle.',
    status: 'Pending Review',
  },
  {
    id: 'ACTION-003',
    urgency: 'Corrective action',
    suspectedCause: 'Etch Chamber Temperature Gradient & CD Bias',
    evidence: 'Thermal reading in Bay 3 reached 22.4°C; CD variation delta spiked to +1.65nm across edge ring.',
    affectedWafers: ['WFR-300-8841-02', 'WFR-300-8841-05'],
    affectedDiesCount: 29,
    confidenceScore: 76,
    recommendedAction: 'Recalibrate electrostatic chuck (ESC) helium back-side cooling flow and adjust RF power bias by -1.5% on edge zone tuning ring.',
    expectedEffect: 'Harmonize CD uniformity to within ±0.6nm 3-sigma across whole wafer surface.',
    verificationStep: 'Measure 49-point inline CD-SEM line-width profile on subsequent test wafer.',
    status: 'Pending Review',
  },
  {
    id: 'ACTION-004',
    urgency: 'Verification on the next test layer',
    suspectedCause: 'Edge-Exclusion Zone Mechanical Handling Scratch',
    evidence: 'Arc-shaped defect line traversing columns 18-22 within 5mm of wafer edge notch.',
    affectedWafers: ['WFR-300-8841-06'],
    affectedDiesCount: 14,
    confidenceScore: 91,
    recommendedAction: 'Inspect robot end-effector vacuum wand pads and aligner pre-orientation edge roller for physical burrs or carbon wear.',
    expectedEffect: 'Prevent arc scratch formation on delicate Low-K dielectric passivation layers.',
    verificationStep: 'Optical bright-field macro inspection on dummy bare silicon wafer after 50 handling cycles.',
    status: 'Pending Review',
  },
];

export const TECHNICAL_TOOLTIPS: Record<string, string> = {
  particleContamination: 'Airborne or surface particulates counted per square centimeter. In sub-10nm nodes, particles as small as 15nm can bridge interconnects or block exposure beams.',
  lithoAlignmentError: 'Overlay offset (measured in nanometers) between the current mask layer and prior fiducials. Misalignment causes shorts, open vias, and parasitic capacitance.',
  cdDeviation: 'Critical Dimension deviation measures the discrepancy between nominal feature width (e.g., gate length) and actual etched silicon width. Deviations impact transistor drive current and leakage.',
  temperature: 'Ambient cleanroom temperature. Variations of even 0.5°C cause thermal expansion of quartz reticles, precision mirrors, and wafer stages, creating overlay drift.',
  relativeHumidity: 'Relative humidity impacts chemical amplification in deep UV resists and static electrostatic discharge (ESD) risks. High RH can also hydrolyze sensitive precursors.',
  defectRate: 'Calculated as: Defective Dies / Total Dies × 100%. Represents the percentage of fabricated dies exhibiting severe or fatal functional flaws.',
  dieYield: 'Calculated as: Good Dies / Total Dies × 100%. High-yield wafers maximize fab profitability and silicon economic return.',
  qualityClass: 'Engineered multi-parametric classification (Excellent, Acceptable, Watch, At Risk, Reject for Review) summarizing die yield, defect density, and excursion severity.',
  edgeExclusion: 'A 2mm to 5mm circular boundary along the outermost rim of the wafer where mechanical clamp contact and fluid spin-off preclude functional die fabrication.',
  modelConfidence: 'Rule-engine and statistical certainty score based on parameter consistency, signal-to-noise ratio, and spatial defect correlation.',
};
